spring.application.name=pedidos

spring.datasource.url=jdbc:postgresql://localhost:5432/pedido
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

eureka.client.enabled=false

spring.pid.file=var/run/processid.pid

spring.pid.fail-on-write-error=true